[project]
name = "monitor-and-ranking-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "dotenv>=0.9.9",
    "logfire>=3.14.0",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "seaborn>=0.13.2",
]
